name: Set Random Pair

on:
  schedule:
    - cron: '0 9 * * 4'
  push:
    branches:
      GithubActions_test
env:
  MEMBERS: ${{ secrets.MEMBER }}
  ONLINE_MEMBERS: ${{ secrets.ONLINE }}

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Create ONLINE teams
        run: |
          IFS=' ' read -r -a ALL_MEMBERS <<< "$MEMBERS"
          IFS=' ' read -r -a ONLINE <<< "$ONLINE_MEMBERS"
          
          BEGINNING_NAMES=()
          for member in "${ALL_MEMBERS[@]}"; do
            if [[ ! " ${ONLINE[@]} " =~ " ${member} " ]]; then
              BEGINNING_NAMES+=("$member")
            fi
          done
          
          echo "ONLINE TEAM Size : ${#ONLINE[@]}"

          Shuffle_OFFLINE_teams() {
              SHUFFLED_NAMES=()
              MEMBER_INDEX=0
              while [ ${#BEGINNING_NAMES[@]} -gt 0 ]; 
              do
                RANDOM_INDEX=$(($RANDOM+$RANDOM))
                INDEX=$(( RANDOM_INDEX % ${#BEGINNING_NAMES[@]} ))
                SHUFFLED_NAMES[$MEMBER_INDEX]="${BEGINNING_NAMES[$INDEX]}"
                BEGINNING_NAMES=(${BEGINNING_NAMES[@]:0:$INDEX} ${BEGINNING_NAMES[@]:$((INDEX+1))})
                ((MEMBER_INDEX++))
              done
          }
          
        
          Create_OFFLINE_teams() {
              echo "SHUFFLED_NAMES : ${SHUFFLED_NAMES[@]}"
              DEFAULT_TEAM_SIZE=3
              COLUMN_SIZE=5
              TEAM_COUNT=$(( ${#SHUFFLED_NAMES[@]} / DEFAULT_TEAM_SIZE ))
              declare -A TEAMS
              
              for ((i=1; i<=TEAM_COUNT; i++)); 
              do
                for ((j=1; j<=COLUMN_SIZE+1; j++)); 
                do
                  if [[ ${#SHUFFLED_NAMES[@]} == 0 ]]; then
                      TEAMS["TEAM_$j"]="${TEAMS["TEAM_$j"]} |"
                      continue
                  fi
              
                  RANDOM_INDEX=$RANDOM
                  INDEX=$(( RANDOM_INDEX % ${#SHUFFLED_NAMES[@]} ))
                  TEAMS["TEAM_$j"]="${TEAMS["TEAM_$j"]} | ${SHUFFLED_NAMES[$INDEX]}"
                  echo "RANDOM : $RANDOM_INDEX   RANDOM_INDEX : $INDEX  ,  TEAM_$j 추가: ${SHUFFLED_NAMES[$INDEX]}"
                  SHUFFLED_NAMES=(${SHUFFLED_NAMES[@]:0:$INDEX} ${SHUFFLED_NAMES[@]:$((INDEX+1))})
                done
              done
              
              for ((j=1; j<=TEAM_COUNT; j++)); do
                echo "TEAM_$j: ${TEAMS["TEAM_$j"]}"
              done
          }
          
          
          Shuffle_OFFLINE_teams()
          Create_OFFLINE_teams()
          

      - name: Make Message
        run: |
          
          IFS=' ' read -r -a TEAMS <<< "$TEAMS"
          NEXT_WEEK_MONTH=$(date --date="next week" +%-m)
          NEXT_WEEK_DATE=$(date --date="next week" +%-d)
          NEXT_WEEK_NUM=$((NEXT_WEEK_DATE/7 + 1))
          
          if [ $((NEXT_WEEK_DATE % 7)) -eq 0 ]; then
            $((NEXT_WEEK_NUM--))
          fi
          echo "$NEXT_WEEK_MONTH 월 $NEXT_WEEK_DATE 일 $NEXT_WEEK_NUM 주차"
          
          MESSAGE="\"| Pair |$NEXT_WEEK_MONTH 월 | $NEXT_WEEK_NUM 주차 ||| 비고 |\\n"
          MESSAGE+="|---|---|---|---|---|---|\\n"
          for ((i=1; i<=$TEAM_COUNT; i++))
            do
              MESSAGE+="|$i."
              MESSAGE+="${TEAMS["TEAM_$i"]}"
              MESSAGE+="\\n"
            done
          
          MESSAGE+="||"
          for ((i=0; i<$COLUMN_SIZE -1 ; i++))
          do
            if (( i > ${#ONLINE[@]} )); then
              MESSAGE+="|"
            else
              MESSAGE+="${ONLINE[$i]}|"
            fi
          done
          MESSAGE+="온라인|\\n\""
          echo "$MESSAGE"
          
          curl -X POST -H 'Content-type: application/json' --data "{\"text\": $MESSAGE}" ${{ secrets.WEBHOOK }}
